package io.github.aasaru.drools.section06.step7

unit Section06RuleUnit

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import java.time.LocalDate
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
  dialect "java"
  agenda-group "issue-visa"
  when
    $visaApplication: /visaApplications[ validation == Validation.PASSED ]
  then
    Visa visa = new Visa( $visaApplication.getPassportNumber() );
    System.out.println("Issue " + visa);
    visas.insert(visa);
end
