package io.github.aasaru.drools.chapter04

import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
    dialect "mvel"
    when
        $visaApplication: FamilyVisaApplication( )
        exists Passport( validationPassed == false, $passportNumber : passportNumber, $visaApplication.passportNumbers.contains(passportNumber))
    then
        System.out.println( "Set visa application " + $visaApplication.getApplicationId() + " invalid as it contains passport that hasn't passed validation");
        $visaApplication.setValidationPassed(false);
end
