package io.github.aasaru.drools.section07

import io.github.aasaru.drools.domain.InvalidVisaApplication;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;

import java.time.LocalDate;


rule "Invalidate visa application where passport expires earlier than 6 months after visit end date"
  dialect "mvel"
  when
    $passport: Passport()
    $visaApplication: VisaApplication( passportNumber == $passport.passportNumber,
                       $passport.expiresOn.isBefore(visitEndDate.plusMonths(6)) )
    not ( InvalidVisaApplication( this.visaApplication == $visaApplication ) )
  then
    System.out.println( "Set " + $visaApplication + " invalid as " + $passport + " is not valid 6 months after planned visit end date");
    insert( new InvalidVisaApplication($visaApplication) )
end