package io.github.aasaru.droolsoopath.section03.step4

unit PassportRuleUnit;

import io.github.aasaru.drools.domain.Validation;

rule "Valid passport"
  dialect "java"
  when
	$passport: /passports[ !isExpired(), $unusedPages: unusedVisaPages > 0 ]
  then
	System.out.println( $passport + " is CORRECT. It has " + $unusedPages + " pages free." );
	$passport.setValidation( Validation.PASSED );
end

rule "Expired passport"
  dialect "java"
  when
	$passport: /passports[ isExpired() ]
  then
	System.out.println( $passport + " is INVALID because it is expired" );
	$passport.setValidation( Validation.FAILED );
end

rule "Full passport"
  dialect "java"
  when
	$passport: /passports[ unusedVisaPages == 0 ]
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );
	$passport.setValidation( Validation.FAILED );
end
