package io.github.aasaru.droolsoopath.section03.step2

unit PassportRuleUnit;

rule "Valid passport"
  dialect "java"
  when
	/passports[ !isExpired(), unusedVisaPages > 0 ]
  then
	System.out.println( "This passport is CORRECT" );
end

rule "Expired passport"
  dialect "java"
  when
	/passports[ isExpired() ]
  then
	System.out.println( "This passport is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	/passports[ unusedVisaPages == 0 ]
  then
	System.out.println( "This passport is INVALID because it has no space for visa" );
end
