package io.github.aasaru.drools8.section08.step2

unit RuleUnitSection08;

import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;
import io.github.aasaru.drools.domain.Visa;

import java.time.LocalDate;

rule "Issue visas for valid applications"
	dialect "java"
	when
		$familyVisaApplication: /familyVisaApplications
		not ( InvalidFamilyVisaApplication( this.familyVisaApplication == $familyVisaApplication ) )
	then
		for (String passportNumber : $familyVisaApplication.getPassportNumbers()) {
		  System.out.println( "Issue visa for passport number " + passportNumber);
		  insertLogical( new Visa( passportNumber ) );
		}
end
