package io.github.aasaru.drools.chapter03
 
import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.ValidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import java.time.LocalDate;

rule "Valid passport"
    dialect "mvel"
    when
        $passport: Passport( validation == Validation.UNKNOWN )
    then
        System.out.println( $passport + " is without validation info, consider OK for now" );
        insert( new ValidPassport($passport) )
end

rule "Expired passport"
    dialect "mvel"
    when
        $passport: Passport( isExpired()  )
    then
        System.out.println( $passport + " is INVALID because it is expired" );
        insert( new InvalidPassport($passport) )
end

rule "Full passport"
    dialect "mvel"
    when
        $passport: Passport( unusedVisaPages == 0   )
    then
        System.out.println( $passport + " is INVALID because it has no space for visa" );
        insert( new InvalidPassport($passport) )
end
