package io.github.aasaru.drools.chapter01
 
import io.github.aasaru.drools.chapter01.PassportValidation.Passport;
import java.time.LocalDate;

rule "If no validationPassed info present then consider OK"
    dialect "mvel"
    when
        $passport: Passport( validationPassed == null  )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is without validation info, consider OK for now");
        modify($passport) {
          setValidationPassed(true)
        }
end

rule "Expired passport"
    dialect "mvel"
    when
        $passport: Passport( isExpired()  )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is INVALID because it is expired ");
        modify($passport) {
          setValidationPassed(false)
        }
end

rule "Full passport"
    dialect "mvel"
    when
        $passport: Passport( unusedVisaPages == 0   )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is INVALID because it has no space for visa");
        modify($passport) {
          setValidationPassed(false)
        }
end
