package io.github.aasaru.drools.chapter01
 
import io.github.aasaru.drools.domain.Passport;
import java.time.LocalDate
import io.github.aasaru.drools.domain.Validation;

rule "Valid passport"
    dialect "mvel"
    when
        $passport: Passport( !isExpired(), unusedVisaPages > 0  )
    then
        System.out.println( $passport + " is CORRECT" );
        $passport.setValidation( Validation.PASSED );
end

rule "Expired passport"
    dialect "mvel"
    when
        $passport: Passport( isExpired()  )
    then
        System.out.println( $passport + " is INVALID because it is expired" );
        $passport.setValidation( Validation.FAILED );
end

rule "Full passport"
    dialect "mvel"
    when
        $passport: Passport( unusedVisaPages == 0   )
    then
        System.out.println( $passport + " is INVALID because it has no space for visa" );
        $passport.setValidation( Validation.FAILED );
end
