package io.github.aasaru.drools8.section07.step3

unit Section07RuleUnit;

import io.github.aasaru.drools.domain.ValidVisaApplication;
import io.github.aasaru.drools.domain.VisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
	dialect "java"
	when
	  /validVisaApplications[ $visaApplication: this.visaApplication ]
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  visas.addLogical( visa );
end
