package io.github.aasaru.drools.section08.step5

import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Issue visas for valid applications"
	dialect "java"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		not ( InvalidFamilyVisaApplication( this.familyVisaApplication == $familyVisaApplication ) )
	then
		for (String passportNumber : $familyVisaApplication.getPassportNumbers()) {
		  System.out.println( "Issue visa for passport number " + passportNumber);
		  insertLogical( new Visa( passportNumber ) );
		}
end
