package io.github.aasaru.drools.section08.step5

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import java.time.LocalDate;


rule "Everyone is at least 20"
	dialect "mvel"
	when
		forall ( Passport( age >= 20 ))
	then
		System.out.println( "Everyone whose passport is in session is at least 20 years old" );
end
