package io.github.aasaru.droolsoopath.section03.step3

unit PassportRuleUnit;

rule "Valid passport"
  dialect "java"
  when
	$passport: /passports[ !isExpired(), $unusedPages: unusedVisaPages > 0 ]
  then
	System.out.println( $passport + " is CORRECT. It has " + $unusedPages + " pages free." );
end

rule "Expired passport"
  dialect "java"
  when
	$passport: /passports[ isExpired() ]
  then
	System.out.println( $passport + " is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	$passport: /passports[ unusedVisaPages == 0 ]
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );
end
