package io.github.aasaru.drools.section07.step1

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
	dialect "java"
	when
	  $visaApplication: VisaApplication( validation == Validation.PASSED )
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insertLogical( visa );
end
