package io.github.aasaru.droolsoopath.section06.step2

unit RuleUnitSection06;

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
  dialect "java"
  salience -100
  when
    $visaApplication: /visaApplications[ validation == Validation.PASSED ]
  then
    Visa visa = new Visa( $visaApplication.getPassportNumber() );
    System.out.println("Issue " + visa);
    visas.append(visa);
end
