package io.github.aasaru.drools.chapter02

import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.VisaApplication;

import java.time.LocalDate;

rule "Invalidate visa application that has planned visit start date set after planned visit end date"
    dialect "mvel"
    when
        $visaApplication: VisaApplication( visitStartDate.isAfter(visitEndDate) )
    then
        System.out.println( "Visa Application (" + $visaApplication.getPassportNumber() + ") has visit start date set after visit end date");
        $visaApplication.setValidationPassed(false);
end

rule "Invalidate visa application that has planned visit start date in the past"
    dialect "mvel"
    when
        $visaApplication: VisaApplication( visitStartDate.isBefore(LocalDate.now()) )
    then
        System.out.println( "Visa Application (" + $visaApplication.getPassportNumber() + ") has planned visit start date is in the past");
        $visaApplication.setValidationPassed(false);
end