package io.github.aasaru.drools.section06.step2
 
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;

rule "Valid passport"
  dialect "java"
  salience 50
  when
    $passport: Passport( validation == Validation.UNKNOWN )
  then
    System.out.println( $passport + " is without validation info, consider OK for now" );
    modify($passport) {
      setValidation( Validation.PASSED )
    }
end

rule "Expired passport"
  dialect "java"
  salience 60
  when
    $passport: Passport( isExpired()  )
  then
    System.out.println( $passport + " is INVALID because it is expired" );
    modify($passport) {
      setValidation( Validation.FAILED ),
      setCause( "passport is expired" )
    }
end

rule "Full passport"
  dialect "java"
  salience 60
  when
    $passport: Passport( unusedVisaPages == 0   )
  then
    System.out.println( $passport + " is INVALID because it has no space for visa" );
    modify($passport) {
      setValidation( Validation.FAILED ),
      setCause( "passport has no space for visa" )
    }
end
