package io.github.aasaru.drools8.section06.step2

unit PassportVisaApplicationVisaRuleUnit;

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import java.time.LocalDate
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
  dialect "java"
  salience -100
  when
    $visaApplication: /visaApplications[ validation == Validation.PASSED ]
  then
    Visa visa = new Visa( $visaApplication.getPassportNumber() );
    System.out.println("Issue " + visa);
    visas.add(visa);
end
