package io.github.aasaru.drools8.section08.step5

unit RuleUnitSection08;

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import java.time.LocalDate;


rule "Everyone is at least 10"
	dialect "java"
	when
		forall ( Passport( age >= 10 ))
	then
		System.out.println( "Everyone whose passport is in session is at least 10 years old" );
end
