package io.github.aasaru.drools.section06.step3

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
  dialect "java"
  agenda-group "issue-visa"
  when
    $visaApplication: VisaApplication( validation == Validation.PASSED )
  then
    Visa visa = new Visa( $visaApplication.getPassportNumber() );
    System.out.println("Issue " + visa);
    insert( visa );
end
