package io.github.aasaru.drools.chapter02

import io.github.aasaru.drools.chapter02.VisaApplicationValidation.Passport;
import io.github.aasaru.drools.chapter02.VisaApplicationValidation.VisaApplication;

import java.time.LocalDate;

rule "Applicable for visa"
    dialect "mvel"
    when
        Passport( isValid(), $passportNr : passportNumber, $passportExpireDate : expiresOn)
        VisaApplication( passportNumber == $passportNr, visitEndDate.plusMonths(6).isBefore($passportExpireDate) )
    then
        System.out.println( "Passport " + $passportNr + " is valid 6 months after travel end date");
end

