package io.github.aasaru.drools.chapter02

import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;

import java.time.LocalDate;

rule "Invalidate visa application that has planned visit start date set after planned visit end date"
    dialect "mvel"
    when
        $visaApplication: VisaApplication( /* TODO fill here: */ visitStartDate.isAfter(visitEndDate) )
    then
        System.out.println( $visaApplication + " has visit start date set after visit end date");
        $visaApplication.setValidation( Validation.FAILED );
end

rule "Invalidate visa application that has planned visit start date in the past"
    dialect "mvel"
    when
        $visaApplication: VisaApplication( /* TODO fill here: */ visitStartDate.isBefore(LocalDate.now()) )
    then
        System.out.println( $visaApplication + " has planned visit start date is in the past");
        $visaApplication.setValidation( Validation.FAILED );
end