package io.github.aasaru.drools.section06

import io.github.aasaru.drools.domain.Visa;

rule "Report were visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 20
	when
    Visa()
	then
	  System.out.println("Conclusion: at least one visa was issued");
end

rule "Report no visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 10
	when
    not Visa()
	then
	  System.out.println("Conclusion: no visas were issued");
end
