package io.github.aasaru.drools.section06.step5

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Report were visas"
  dialect "java"
  activation-group "conclusion"
  salience 20
  when
    Visa()
  then
    System.out.println("Conclusion: at least one visa was issued");
end

rule "Report no visas"
  dialect "java"
  activation-group "conclusion"
  salience 10
  when
    VisaApplication( validation == Validation.FAILED )
  then
    System.out.println("Conclusion: no visas were issued");
end
