package io.github.aasaru.drools.chapter01
 
import io.github.aasaru.drools.chapter01.PassportValidation.Passport;
import java.time.LocalDate;

rule "Valid passport"
    dialect "mvel"
    when
        $passport: Passport( !isExpired(), unusedVisaPages > 0  )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is OK");
end

rule "Expired passport"
    dialect "mvel"
    when
        $passport: Passport( isExpired()  )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is INVALID because it is expired ");
end

rule "Full passport"
    dialect "mvel"
    when
        $passport: Passport( unusedVisaPages == 0   )
    then
        System.out.println("Passport " + $passport.getPassportNumber() + " is INVALID because it has no space for visa");
end
