package io.github.aasaru.drools.chapter05

import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.InvalidVisaApplication;
import io.github.aasaru.drools.domain.VisaApplication;
import java.time.LocalDate
import io.github.aasaru.drools.domain.Visa;

rule "Issue visa for valid applications"
    dialect "mvel"
    when
      $visaApplication: VisaApplication( )
      not InvalidPassport( this.passport.passportNumber == $visaApplication.passportNumber )
      not InvalidVisaApplication( this.visaApplication == $visaApplication )
    then
      Visa visa = new Visa( $visaApplication.getPassportNumber() );
      System.out.println("Issue " + visa);
      insertLogical( visa )
end