package io.github.aasaru.drools8.section03.step2

unit PassportRuleUnit;

import io.github.aasaru.drools.domain.Passport;
import java.time.LocalDate;

rule "Valid passport"
  dialect "java"
  when
	/passports[ !isExpired(), unusedVisaPages > 0 ]
  then
	System.out.println( "This passport is CORRECT" );
end

rule "Expired passport"
  dialect "java"
  when
	/passports[ isExpired() ]
  then
	System.out.println( "This passport is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	/passports[ unusedVisaPages == 0 ]
  then
	System.out.println( "This passport is INVALID because it has no space for visa" );
end
