package io.github.aasaru.drools.section08

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		$passport: Passport( $familyVisaApplication.passportNumbers.contains(passportNumber) )
		InvalidPassport( this.passport == $passport )
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) )
end
