package io.github.aasaru.drools.section08.step3

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;

rule "Invalidate visa applications with invalid passport"
	dialect "java"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		exists InvalidPassport( $familyVisaApplication.passportNumbers.contains(this.passport.passportNumber) )
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) );
end

rule "Invalidate visa application where everyone is under 16"
	dialect "java"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		forall (
        $passport : Passport( $familyVisaApplication.passportNumbers.contains(this.passportNumber) ),
                    Passport( this == $passport, this.age < 16)
		)
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as everyone is younger than 16");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) );
end
