package io.github.aasaru.drools8.section08.step1

unit RuleUnitSection08;

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
	dialect "java"
	when
		$familyVisaApplication: /familyVisaApplications
		$ip: /invalidPassports[ $familyVisaApplication.passportNumbers.contains(this.passport.passportNumber) ]
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		invalidFamilyVisaApplications.add( new InvalidFamilyVisaApplication($familyVisaApplication) );
end
